// Export utilities: Markdown, TXT, PDF, DOCX, PPTX.

import jsPDF from 'jspdf';
import {
  Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
} from 'docx';
import pptxgen from 'pptxgenjs';

function fileBase(title: string) {
  return title.replace(/[^\w\s-]/g, '').replace(/\s+/g, '-').toLowerCase() || 'studyforge';
}

function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function exportMarkdown(content: string, title: string) {
  download(new Blob([content], { type: 'text/markdown;charset=utf-8' }), `${fileBase(title)}.md`);
}
export function exportTxt(content: string, title: string) {
  const plain = content.replace(/^#+\s*/gm, '').replace(/[*_`]/g, '');
  download(new Blob([plain], { type: 'text/plain;charset=utf-8' }), `${fileBase(title)}.txt`);
}

// ---------- PDF ----------
export function exportPdf(content: string, title: string) {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const margin = 56;
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const maxW = pageW - margin * 2;
  let y = margin;

  const ensureSpace = (h: number) => {
    if (y + h > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Cover
  doc.setFont('helvetica', 'bold'); doc.setFontSize(22);
  doc.text(title, margin, y); y += 28;
  doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(120);
  doc.text(`Generated by StudyForge · ${new Date().toLocaleDateString()}`, margin, y); y += 24;
  doc.setTextColor(20);

  const lines = content.split('\n');
  let inCode = false;
  for (const raw of lines) {
    const line = raw.replace(/\r$/, '');
    if (line.trim().startsWith('```')) { inCode = !inCode; y += 6; continue; }
    if (!line.trim()) { y += 8; continue; }

    let text = line;
    let size = 11;
    let style: 'normal' | 'bold' = 'normal';
    let indent = 0;

    if (/^#\s+/.test(line)) { text = line.replace(/^#\s+/, ''); size = 18; style = 'bold'; y += 6; }
    else if (/^##\s+/.test(line)) { text = line.replace(/^##\s+/, ''); size = 14; style = 'bold'; y += 4; }
    else if (/^###\s+/.test(line)) { text = line.replace(/^###\s+/, ''); size = 12; style = 'bold'; y += 2; }
    else if (/^\s*[-*+]\s+/.test(line)) { text = '• ' + line.replace(/^\s*[-*+]\s+/, ''); indent = 12; }
    else if (/^\s*\d+\.\s+/.test(line)) { indent = 12; }
    else if (inCode) { size = 9; style = 'normal'; }

    text = text.replace(/\*\*(.+?)\*\*/g, '$1').replace(/[*_`]/g, '');

    doc.setFont(inCode ? 'courier' : 'helvetica', style);
    doc.setFontSize(size);
    const wrapped = doc.splitTextToSize(text, maxW - indent);
    for (const w of wrapped) {
      ensureSpace(size + 4);
      doc.text(w, margin + indent, y);
      y += size + 4;
    }
  }

  doc.save(`${fileBase(title)}.pdf`);
}

// ---------- DOCX ----------
export async function exportDocx(content: string, title: string) {
  const children: Paragraph[] = [
    new Paragraph({
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.LEFT,
      children: [new TextRun({ text: title, bold: true, size: 44 })],
    }),
    new Paragraph({
      children: [new TextRun({ text: `Generated by StudyForge · ${new Date().toLocaleDateString()}`, italics: true, color: '888888' })],
    }),
    new Paragraph({ text: '' }),
  ];

  const lines = content.split('\n');
  let inCode = false;
  let codeBuf: string[] = [];

  const flushCode = () => {
    if (!codeBuf.length) return;
    for (const c of codeBuf) {
      children.push(new Paragraph({ children: [new TextRun({ text: c || ' ', font: 'Consolas', size: 20 })] }));
    }
    codeBuf = [];
  };

  for (const raw of lines) {
    const line = raw.replace(/\r$/, '');
    if (line.trim().startsWith('```')) {
      inCode = !inCode;
      if (!inCode) flushCode();
      continue;
    }
    if (inCode) { codeBuf.push(line); continue; }

    if (!line.trim()) { children.push(new Paragraph({ text: '' })); continue; }

    let m;
    if ((m = line.match(/^#\s+(.+)/))) {
      children.push(new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: m[1].replace(/[*_`]/g, ''), bold: true })] }));
    } else if ((m = line.match(/^##\s+(.+)/))) {
      children.push(new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun({ text: m[1].replace(/[*_`]/g, ''), bold: true })] }));
    } else if ((m = line.match(/^###\s+(.+)/))) {
      children.push(new Paragraph({ heading: HeadingLevel.HEADING_3, children: [new TextRun({ text: m[1].replace(/[*_`]/g, ''), bold: true })] }));
    } else if ((m = line.match(/^\s*[-*+]\s+(.+)/))) {
      children.push(new Paragraph({ bullet: { level: 0 }, children: parseRuns(m[1]) }));
    } else if ((m = line.match(/^\s*(\d+)\.\s+(.+)/))) {
      children.push(new Paragraph({ children: [new TextRun({ text: `${m[1]}. ` }), ...parseRuns(m[2])] }));
    } else if (line.startsWith('>')) {
      children.push(new Paragraph({ indent: { left: 360 }, children: [new TextRun({ text: line.replace(/^>\s?/, '').replace(/[*_`]/g, ''), italics: true, color: '666666' })] }));
    } else if (line.startsWith('|')) {
      // simple table row as plain text
      children.push(new Paragraph({ children: [new TextRun({ text: line.replace(/\|/g, '   ').replace(/[*_`]/g, ''), font: 'Calibri' })] }));
    } else {
      children.push(new Paragraph({ children: parseRuns(line) }));
    }
  }
  flushCode();

  const doc = new Document({ sections: [{ children }] });
  const blob = await Packer.toBlob(doc);
  download(blob, `${fileBase(title)}.docx`);
}

function parseRuns(text: string): TextRun[] {
  const out: TextRun[] = [];
  const re = /\*\*(.+?)\*\*|`(.+?)`|(.+?)(?=\*\*|`|$)/g;
  let m;
  while ((m = re.exec(text)) !== null) {
    if (m[1]) out.push(new TextRun({ text: m[1], bold: true }));
    else if (m[2]) out.push(new TextRun({ text: m[2], font: 'Consolas' }));
    else if (m[3]) out.push(new TextRun({ text: m[3] }));
  }
  if (!out.length) out.push(new TextRun({ text }));
  return out;
}

// ---------- PPTX ----------
export async function exportPptx(content: string, title: string) {
  const pptx = new pptxgen();
  pptx.layout = 'LAYOUT_WIDE';
  pptx.title = title;

  // Section-split by H1/H2
  const sections: { title: string; bullets: string[] }[] = [];
  let current: { title: string; bullets: string[] } | null = null;
  const lines = content.split('\n');
  let inCode = false;

  for (const raw of lines) {
    const line = raw.replace(/\r$/, '');
    if (line.trim().startsWith('```')) { inCode = !inCode; continue; }
    if (inCode) continue;
    let m;
    if ((m = line.match(/^#{1,2}\s+(.+)/))) {
      if (current) sections.push(current);
      current = { title: m[1].replace(/[*_`]/g, ''), bullets: [] };
    } else if ((m = line.match(/^###\s+(.+)/))) {
      if (current) current.bullets.push(m[1].replace(/[*_`]/g, ''));
    } else if ((m = line.match(/^\s*[-*+]\s+(.+)/))) {
      if (current) current.bullets.push(m[1].replace(/[*_`]/g, ''));
    } else if (line.trim() && current && current.bullets.length < 6) {
      const t = line.replace(/[*_`]/g, '').trim();
      if (t.length > 4 && t.length < 200) current.bullets.push(t);
    }
  }
  if (current) sections.push(current);

  // Cover slide
  const cover = pptx.addSlide();
  cover.background = { color: '0F172A' };
  cover.addText(title, { x: 0.7, y: 2.5, w: 11, h: 1.5, fontSize: 44, bold: true, color: 'FFFFFF', fontFace: 'Arial' });
  cover.addText('Generated by StudyForge', { x: 0.7, y: 4.0, w: 11, h: 0.5, fontSize: 16, color: '94A3B8', fontFace: 'Arial' });

  // Content slides — chunk bullets to ≤6 per slide
  for (const sec of sections.slice(0, 30)) {
    const chunks: string[][] = [];
    for (let i = 0; i < Math.max(sec.bullets.length, 1); i += 6) {
      chunks.push(sec.bullets.slice(i, i + 6));
    }
    chunks.forEach((bullets, idx) => {
      const s = pptx.addSlide();
      s.background = { color: 'FFFFFF' };
      s.addText(sec.title + (chunks.length > 1 ? ` (${idx + 1}/${chunks.length})` : ''), {
        x: 0.5, y: 0.4, w: 12, h: 0.8, fontSize: 28, bold: true, color: '0F172A', fontFace: 'Arial',
      });
      s.addShape(pptx.ShapeType.line, { x: 0.5, y: 1.15, w: 1.5, h: 0, line: { color: '6366F1', width: 3 } });
      if (bullets.length) {
        s.addText(
          bullets.map(b => ({ text: b, options: { bullet: { code: '25CF' }, paraSpaceAfter: 8 } })),
          { x: 0.7, y: 1.4, w: 11.5, h: 5.5, fontSize: 18, color: '334155', fontFace: 'Arial', valign: 'top' }
        );
      }
      s.addText('StudyForge', { x: 0.5, y: 7.0, w: 5, h: 0.3, fontSize: 10, color: '94A3B8', fontFace: 'Arial' });
    });
  }

  await pptx.writeFile({ fileName: `${fileBase(title)}.pptx` });
}
