// Export interactive/visual artifacts to HTML, PNG, and PDF.

import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import type { ComicResult, InfographicResult } from './visual-api';

function fileBase(t: string) {
  return t.replace(/[^\w\s-]/g, '').replace(/\s+/g, '-').toLowerCase() || 'studyforge';
}
function download(blob: Blob, name: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = name;
  document.body.appendChild(a); a.click(); a.remove();
  URL.revokeObjectURL(url);
}

// ---------- Snapshot of any DOM element ----------
export async function exportElementAsPng(el: HTMLElement, name: string) {
  const canvas = await html2canvas(el, { backgroundColor: '#ffffff', scale: 2, useCORS: true });
  const blob = await new Promise<Blob>(r => canvas.toBlob(b => r(b!), 'image/png'));
  download(blob, `${fileBase(name)}.png`);
}

export async function exportElementAsPdf(el: HTMLElement, name: string) {
  const canvas = await html2canvas(el, { backgroundColor: '#ffffff', scale: 2, useCORS: true });
  const img = canvas.toDataURL('image/png');
  const pdf = new jsPDF({ orientation: canvas.width > canvas.height ? 'landscape' : 'portrait', unit: 'pt', format: 'a4' });
  const pw = pdf.internal.pageSize.getWidth();
  const ph = pdf.internal.pageSize.getHeight();
  const ratio = Math.min(pw / canvas.width, ph / canvas.height);
  const w = canvas.width * ratio;
  const h = canvas.height * ratio;
  pdf.addImage(img, 'PNG', (pw - w) / 2, (ph - h) / 2, w, h);
  pdf.save(`${fileBase(name)}.pdf`);
}

// ---------- Comic Strip HTML ----------
export function exportComicAsHtml(c: ComicResult) {
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<title>${escapeHtml(c.title)}</title>
<style>
  body { font-family: 'Georgia', serif; background:#f5f1e8; margin:0; padding:40px; color:#1a1a1a; }
  .book { max-width: 1100px; margin:0 auto; }
  h1 { font-size: 48px; margin: 0 0 8px; letter-spacing:-1px; }
  .sub { font-style: italic; color:#5a5a5a; margin-bottom: 32px; }
  .grid { display:grid; grid-template-columns: repeat(2, 1fr); gap: 24px; }
  .panel { background:#fff; border:4px solid #111; border-radius: 10px; overflow:hidden; box-shadow: 6px 6px 0 #111; display:flex; flex-direction:column; }
  .panel .img { aspect-ratio: 1/1; background:#eee; position:relative; }
  .panel img { width:100%; height:100%; object-fit:cover; display:block; }
  .bubble { position:absolute; top:12px; left:12px; background:#fff; border:2.5px solid #111; border-radius: 18px; padding: 8px 12px; max-width: 60%; font-weight:600; font-family: 'Comic Sans MS', system-ui, sans-serif; box-shadow: 3px 3px 0 #111; }
  .meta { padding: 14px 16px; border-top: 3px solid #111; }
  .ptitle { font-weight:800; text-transform:uppercase; font-size:13px; letter-spacing:1px; color:#b91c1c; margin-bottom:6px; }
  .cap { font-size:15px; line-height:1.45; }
  footer { text-align:center; margin-top:40px; font-size:12px; color:#666; }
</style></head>
<body><div class="book">
<h1>${escapeHtml(c.title)}</h1>
<p class="sub">${escapeHtml(c.subtitle || '')} · Style: ${escapeHtml(c.style || '')}</p>
<div class="grid">
${c.panels.map((p, i) => `
  <div class="panel">
    <div class="img">
      ${p.image && isSafeImageUrl(p.image) ? `<img src="${escapeHtml(p.image)}" alt="${escapeHtml(p.title)}"/>` : '<div style="display:flex;align-items:center;justify-content:center;height:100%;color:#999">(image unavailable)</div>'}
      ${p.dialogue ? `<div class="bubble">${escapeHtml(p.dialogue)}</div>` : ''}
    </div>
    <div class="meta">
      <div class="ptitle">Panel ${i + 1} · ${escapeHtml(p.title)}</div>
      <div class="cap">${escapeHtml(p.caption)}</div>
    </div>
  </div>`).join('')}
</div>
<footer>Generated by StudyForge</footer>
</div></body></html>`;
  download(new Blob([html], { type: 'text/html;charset=utf-8' }), `${fileBase(c.title)}-comic.html`);
}

// ---------- Infographic HTML ----------
export function exportInfographicAsHtml(g: InfographicResult) {
  const p = {
    primary: safeHex(g.palette?.primary, '#2563eb'),
    secondary: safeHex(g.palette?.secondary, '#0ea5e9'),
    accent: safeHex(g.palette?.accent, '#f59e0b'),
    bg: safeHex(g.palette?.bg, '#f8fafc'),
  };
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<title>${escapeHtml(g.title)}</title>
<style>
  body { font-family: 'Inter', system-ui, sans-serif; background:${p.bg}; margin:0; padding:0; color:#0f172a; }
  .wrap { max-width: 980px; margin:0 auto; padding: 56px 40px; }
  h1 { font-size: 52px; line-height:1.05; margin:0 0 12px; color:${p.primary}; letter-spacing:-1.5px; }
  .sub { font-size: 20px; color:#475569; margin: 0 0 36px; max-width: 720px; }
  .takeaway { background:${p.primary}; color:#fff; padding: 28px 32px; border-radius: 18px; font-size: 22px; font-weight: 600; margin-bottom: 40px; line-height:1.35; }
  .stats { display:grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin-bottom: 48px; }
  .stat { background:#fff; border-radius: 16px; padding: 24px; border: 2px solid ${p.accent}33; }
  .stat .v { font-size: 44px; font-weight: 800; color:${p.accent}; line-height: 1; margin-bottom: 8px; }
  .stat .l { font-size: 14px; font-weight: 600; color:#0f172a; margin-bottom: 6px; }
  .stat .d { font-size: 12px; color:#64748b; }
  .sections { display:grid; gap: 20px; }
  .section { background:#fff; border-left: 6px solid ${p.secondary}; padding: 24px 28px; border-radius: 12px; }
  .section h3 { margin: 0 0 8px; font-size: 22px; color:${p.primary}; }
  .section p { margin: 0; line-height: 1.6; color:#334155; }
  footer { text-align:center; margin-top:48px; font-size:12px; color:#94a3b8; }
</style></head>
<body><div class="wrap">
<h1>${escapeHtml(g.title)}</h1>
<p class="sub">${escapeHtml(g.subtitle)}</p>
<div class="takeaway">★ ${escapeHtml(g.takeaway)}</div>
${g.stats?.length ? `<div class="stats">${g.stats.map(s => `
  <div class="stat">
    <div class="v">${escapeHtml(s.value)}</div>
    <div class="l">${escapeHtml(s.label)}</div>
    ${s.description ? `<div class="d">${escapeHtml(s.description)}</div>` : ''}
  </div>`).join('')}</div>` : ''}
<div class="sections">${g.sections.map(s => `
  <div class="section">
    <h3>${escapeHtml(s.heading)}</h3>
    <p>${escapeHtml(s.body)}</p>
  </div>`).join('')}</div>
<footer>Generated by StudyForge</footer>
</div></body></html>`;
  download(new Blob([html], { type: 'text/html;charset=utf-8' }), `${fileBase(g.title)}-infographic.html`);
}

function escapeHtml(s: string) {
  return String(s ?? '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

function isSafeImageUrl(u: string): boolean {
  if (typeof u !== 'string') return false;
  // Allow http(s) and data:image/* URLs only
  return /^https?:\/\//i.test(u) || /^data:image\/(png|jpe?g|gif|webp|svg\+xml);/i.test(u);
}

function safeHex(c: string, fallback: string): string {
  return typeof c === 'string' && /^#[0-9a-fA-F]{3,8}$/.test(c) ? c : fallback;
}
